language: node_js
node_js:
  - "10.15.3"

cache:
  directories:
    - "node_modules"

env:
  - ELEMENT_IPFS_MULTIADDR="/ip4/127.0.0.1/tcp/5001" ELEMENT_PROVIDER="http://localhost:8545" ELEMENT_MNEUMONIC="hazard pride garment scout search divide solution argue wait avoid title cave"

before_install:
  - npm i -g firebase-tools@6.1.1
  - npm i
  - npm run ganache &>/dev/null &
  - npm run ipfs:init
  - npm run ipfs &>/dev/null &
  - sleep 10
  - curl -s http://localhost:5001/api/v0/id | jq -r '.'
  - curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":0}' http://localhost:8545 | jq -r '.'
  - curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x1e228837561e32a6ec1b16f0574d6a493edc8863", "latest"],"id":1}' http://localhost:8545 | jq -r '.'

install:
  - npm run bootstrap

script:
  - npm run create-local-runtimeconfig
  - npm run test:contracts
  - npm run contracts:migrate:dev
  - npm run lint
  - npm run coverage
  - npm run codecov
